version: '3.3'
services:
    SpectreBot:
        image: ghcr.io/pandeof1/spectre-discordbot:main
        container_name: SpectreBot
        environment:
            - SBOT_DISCORD_USERNAME=Bot Name
            - SBOT_DISCORD_CLIENT_ID=111111111111111111
            - SBOT_DISCORD_TOKEN=xxxxx
            - SBOT_DISCORD_AUTHORISED_CLIENT_IDS=['1111', '11111']
            - SBOT_DISCORD_ROLE_ID=111111111111111111
            - SBOT_DISCORD_ROLE_ID=111111111111111111
            - SBOT_DISCORD_LOG_CHANNEL_ID=111111111111111111
            - SBOT_DISCORD_GUILD_ID=111111111111111111
            - SBOT_DISCORD_STEAM_ID_CHANNEL_ID=111111111111111111
        restart: always